CC=g++
CFLAGS=-c -Wall -O1

VEKTORIAI_SOURCES=vektoriai.cpp mokinys.cpp
TEST_SOURCES=test.cpp

VEKTORIAI_OBJECTS=$(VEKTORIAI_SOURCES:.cpp=.o)
TEST_OBJECTS=$(TEST_SOURCES:.cpp=.o)

VEKTORIAI_EXECUTABLE=vektoriai
TEST_EXECUTABLE=test

all: $(VEKTORIAI_EXECUTABLE) $(TEST_EXECUTABLE)

$(VEKTORIAI_EXECUTABLE): $(VEKTORIAI_OBJECTS)
	$(CC) $(VEKTORIAI_OBJECTS) -o $@

$(TEST_EXECUTABLE): $(TEST_OBJECTS)
	$(CC) $(TEST_OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	del *.o $(VEKTORIAI_EXECUTABLE) $(TEST_EXECUTABLE)
